# Generated by Django 4.2.7 on 2026-02-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('business_type', models.CharField(max_length=200, verbose_name='Тип бизнеса')),
                ('task', models.TextField(verbose_name='Задача')),
                ('deadline', models.CharField(max_length=50, verbose_name='Сроки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Запрос на расчет',
                'verbose_name_plural': 'Запросы на расчет',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Запрос на обратный звонок',
                'verbose_name_plural': 'Запросы на обратный звонок',
                'ordering': ['-created_at'],
            },
        ),
    ]
